import type { Dataset } from '../core/types';
import { applyAging } from '../core/aging';

import games from '../../data/games.json';
import graveyard from '../../data/graveyard.json';
import publishers from '../../data/publishers.json';
import stores from '../../data/stores.json';
import laws from '../../data/laws.json';
import meta from '../../data/meta.json';

/** Snapshot compiled into the app — the offline/first-paint fallback. */
export const bundledDataset = {
  version: meta.version,
  updated: meta.updated,
  games,
  graveyard,
  publishers,
  stores,
  laws,
} as unknown as Dataset;

export type DatasetSource = 'remote' | 'bundled';

export interface LoadedDataset {
  dataset: Dataset;
  source: DatasetSource;
}

/**
 * Remote-first, bundled-fallback. The server publishes /data/dataset.json
 * (regenerated by the daily pipeline), so users get fresh data on every
 * visit without an app update; if the fetch fails (offline, demo build)
 * the bundled snapshot serves. Either way, aging is applied client-side so
 * a stale dataset still renders announced shutdowns correctly.
 */
export async function loadDataset(nowISO: string): Promise<LoadedDataset> {
  let dataset = bundledDataset;
  let source: DatasetSource = 'bundled';
  try {
    const res = await fetch(`${import.meta.env.BASE_URL}data/dataset.json`, {
      headers: { accept: 'application/json' },
    });
    if (res.ok) {
      const remote = (await res.json()) as Dataset;
      if (remote && Array.isArray(remote.games) && remote.version >= bundledDataset.version) {
        dataset = remote;
        source = 'remote';
      }
    }
  } catch {
    /* offline or demo build: bundled snapshot is the product */
  }
  return { dataset: applyAging(dataset, nowISO), source };
}
